### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by molzieyy** [podshumok/python-smpplib#32]
I am getting this error....could you assist
```
Traceback (most recent call last):
  File "python-smpplib/test1.py", line 4, in <module>
    import smpplib.gsm
  File "/root/python-smpplib/smpplib/__init__.py", line 26, in <module>
    from . import client
  File "/root/python-smpplib/smpplib/client.py", line 83
    except (exceptions.PDUError, exceptions.ConnectionError), e:
                                                            ^
```

**Comment by podshumok** [comment]
Python 3 is not supported (yet)

**Comment by podshumok** [comment]
Please, check if current master is working for you

**Comment by eigenein** [comment]
The line is fixed in master.
