### ISSUE TITLE
Bind trouble

### ISSUE THREAD

**Issue by nikoladsp** [podshumok/python-smpplib#54]
Hi,
I am trying to use this library but I am getting bind error:

<pre>
client created
INFO:smpplib.client:Connecting to smpp0.nexmo.com:8000...
connected
DEBUG:smpplib.client:Sending bind_transmitter PDU
DEBUG:smpplib.client:>>0000002b000000020000000000000001623433366139373500354c674f7538644a00736d70700034000000 (43 bytes)
DEBUG:smpplib.client:Waiting for PDU...
DEBUG:smpplib.client:<<00000011800000020000000d0000000100 (17 bytes)
DEBUG:smpplib.client:Read bind_transmitter_resp PDU
Traceback (most recent call last):
  File "test_smpp.py", line 24, in <module>
    client.bind_transmitter(system_id='*****', password='***************', system_type='smpp')
  File "build/bdist.linux-x86_64/egg/smpplib/client.py", line 143, in bind_transmitter
  File "build/bdist.linux-x86_64/egg/smpplib/client.py", line 138, in _bind
smpplib.exceptions.PDUError: ('(13) bind_transmitter_resp: Bind Failed', 13)
WARNING:smpplib.client:Command unbind failed: Incorrect BIND Status for given command. Ignored
INFO:smpplib.client:Disconnecting...
</pre>

Code I used is:

<pre>
import logging
import sys

import smpplib.gsm
import smpplib.client
import smpplib.consts

# if you want to know what's happening
logging.basicConfig(level='DEBUG')

client = smpplib.client.Client('smpp0.nexmo.com', 8000)
print('client created')

# Print when obtain message_id
client.set_message_sent_handler(
    lambda pdu: sys.stdout.write('sent {} {}\n'.format(pdu.sequence, pdu.message_id)))
client.set_message_received_handler(
    lambda pdu: sys.stdout.write('delivered {}\n'.format(pdu.receipted_message_id)))

client.connect()
print('connected')

client.bind_transmitter(system_id='***', password='*********', system_type='smpp')
print('bind finished')

client.unbind()
print('unbind')

client.disconnect()
print('disconnected')

print('ENDE')
</pre>

Can you please tell me am I missing something?

Thank you kindly

**Comment by nikoladsp** [comment]
If anyone ends up with the same problem - turns out length of the password is limited to 9 characters
